### ISSUE TITLE
Max, someone stole your work

### ISSUE THREAD

**Issue by SoK05** [Mrmaxmeier/BombSquad-Community-Mod-Manager#13]
Just look:
https://www.youtube.com/watch?v=iwFsGowvSzU

**Comment by Mrmaxmeier** [comment]
It is a bit scummy to distribute the project without crediting the source but I don't really care and the [license](https://github.com/Mrmaxmeier/BombSquad-Community-Mod-Manager/blob/master/LICENSE) doesn't either.
Because the mod manager updates itself like a mod this doesn't produce broken or otherwise strange installations.
I might add some kind of link to this repository in the future if there is a reason to. (for example issues being reported to YouTube videos instead of here)
