### ISSUE TITLE
Adding some kind of rating to the mods

### ISSUE THREAD

**Issue by Avamander** [Mrmaxmeier/BombSquad-Community-Mod-Manager#8]
Would it be possible to add some kind of rating system to the mod manager? I'd love to sort according to actual opinions.

**Comment by Mrmaxmeier** [comment]
Meaningful sorting options would definitely be nice. Ratings would require writing an small web server though. I've only just recently moved the mod manager from an self-hosted server to GitHub for convenience and stability. Using GitHub for mod downloads and some other system for ratings would be the best solution i guess. I'll look into it.

**Comment by Mrmaxmeier** [comment]
You can test the feature by switching to the `next` branch in the mod manager settings.

:construction: To-Dos: 
- [x] gracefully handle invalid server responses
- [x] make sure the redis instance actually writes to disk / doesn't get flushed
- [x] show amount of ratings
  - [x] label button `Change Rating` instead of `Rate Mod` when already rated
- [x] submit downloads to stat server (opt-in or opt-out?)
- [x] sort by downloads
- [x] test on different devices and BombSquad versions
- [x] remove `playability` ratings
  - [x] implement something tag-like
- [x] update `index.json` and push to `master`

**Comment by SoK05** [comment]
Great idea. Rating mods is good option for sorting minigames. I tested it, nice.
