### ISSUE TITLE
RawGit is enforcing HTTPS and breaking scripts

### ISSUE THREAD

**Issue by bchavez** [Mrmaxmeier/BombSquad-Community-Mod-Manager#9]
Hello,

I'm submitting an issue on behalf of a friend who asked me to take a look at your `installer.py` because it was not working out of the box.

**RawGit** recently forced HTTPS for all connections (but briefly reverted temporarily). See: https://github.com/rgrove/rawgit/issues/114

`installer.py` explicitly downloading JSON and mods using HTTP. When **RawGit** turned on HTTPS, the installer script failed with `network error :(`.

One alternative people seem to be using is `http://raw.githack.com`. Alternatively, another alternative is find a way to get `urllib2` to use an HTTPS stack.

Also, I noticed some scripts like `modManager.py` has some hard coded, `rawgit.com` domains, so don't forget those too. :+1:

**Comment by Mrmaxmeier** [comment]
Thanks for the notice :+1:

I've deliberately disabled download over HTTPS while setting the system up because downloads using `urllib2` and HTTPS failed on Android for some reason (some features of the standard library are probably stripped out to improve file size). Falling back to `raw.githack.com` when HTTPS isn't available seems like a good workaround but I totally understand **RawGit**'s reasoning to force HTTPS...
